# Generated by Django 4.2.10 on 2024-03-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0002_sensorunit_last_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorunit',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
