# Generated by Django 4.2.10 on 2024-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0003_sensorunit_unique_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSensorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=255, unique=True)),
                ('registration_request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
            ],
        ),
    ]
