# Generated by Django 4.2.10 on 2024-03-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0004_pendingsensorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorunit',
            name='alert_value_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorunit',
            name='alert_value_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
