# Generated by Django 4.2.10 on 2024-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0006_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the alert is currently active.'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_timestamp',
            field=models.DateTimeField(blank=True, help_text='The time when the alert was resolved.', null=True),
        ),
    ]
