# Generated by Django 4.2.10 on 2024-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0007_alert_is_active_alert_resolved_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='contents',
            field=models.TextField(blank=True, help_text='Describe what is being grown in the greenhouse.'),
        ),
    ]
