# Generated by Django 4.2.10 on 2024-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0008_greenhouse_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='contents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
