# Generated by Django 4.2.10 on 2024-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0009_alter_greenhouse_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorunit',
            name='data_frequency',
            field=models.IntegerField(default=300, help_text='Frequency in seconds for data transmission.'),
        ),
    ]
