# Generated by Django 4.2.10 on 2024-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0010_sensorunit_data_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorunit',
            name='settings_updated',
            field=models.BooleanField(default=False, help_text='Flag to indicate if settings are updated and pending to be picked up by the sensor.'),
        ),
    ]
