# Generated by Django 4.2.10 on 2024-03-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0011_sensorunit_settings_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorunit',
            name='last_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
