# Generated by Django 4.2.10 on 2024-03-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0012_alter_sensorunit_last_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorunit',
            name='sensor_type',
            field=models.CharField(choices=[('HU', 'Humidity'), ('TE', 'Temperature'), ('SM', 'Soil Humidity'), ('CTH', 'Combination of Temperature and Humidity')], default='TE', max_length=3),
        ),
    ]
