# Generated by Django 4.2.10 on 2024-03-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0013_sensorunit_sensor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_type', models.CharField(max_length=50)),
                ('base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('start_endpoint', models.CharField(blank=True, max_length=200)),
                ('stop_endpoint', models.CharField(blank=True, max_length=200)),
                ('status_endpoint', models.CharField(blank=True, max_length=200)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_systems', to='smart_greenhouse_app.greenhouse')),
            ],
        ),
    ]
