# Generated by Django 4.2.10 on 2024-04-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0014_externalsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorunit',
            name='alert_value_high',
        ),
        migrations.RemoveField(
            model_name='sensorunit',
            name='alert_value_low',
        ),
        migrations.AlterField(
            model_name='sensorunit',
            name='sensor_type',
            field=models.CharField(choices=[('HU', 'Humidity'), ('TE', 'Temperature'), ('SM', 'Soil Moisture'), ('CTH', 'Combination of Temperature and Humidity')], default='TE', max_length=3),
        ),
        migrations.CreateModel(
            name='TemperatureThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_threshold', to='smart_greenhouse_app.sensorunit')),
            ],
        ),
        migrations.CreateModel(
            name='HumidityThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='humidity_threshold', to='smart_greenhouse_app.sensorunit')),
            ],
        ),
    ]
