# Generated by Django 4.2.10 on 2024-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0015_remove_sensorunit_alert_value_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humiditythreshold',
            name='high',
        ),
        migrations.RemoveField(
            model_name='humiditythreshold',
            name='low',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='high',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='low',
        ),
        migrations.AddField(
            model_name='humiditythreshold',
            name='humidity_threshold_high',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='humiditythreshold',
            name='humidity_threshold_low',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='temperaturethreshold',
            name='temperature_threshold_high',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='temperaturethreshold',
            name='temperature_threshold_low',
            field=models.FloatField(default=1),
        ),
    ]
