# Generated by Django 4.2.10 on 2024-04-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0016_remove_humiditythreshold_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
