# Generated by Django 4.2.10 on 2024-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0017_weatherforecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherforecast',
            options={},
        ),
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='created_at',
            new_name='forecast_date',
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='forecast_retrieved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='minimum_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
