# Generated by Django 4.2.10 on 2024-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0019_alter_weatherforecast_forecast_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorunit',
            name='unique_identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
