# Generated by Django 4.2.10 on 2024-04-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0020_alter_sensorunit_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='automated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EnvironmentalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('env_type', models.CharField(choices=[('Cooling', 'Cooling'), ('Heating', 'Heating'), ('Sprinkler', 'Sprinkler')], default='Cooling', max_length=10)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_systems', to='smart_greenhouse_app.greenhouse')),
            ],
        ),
    ]
