# Generated by Django 4.2.10 on 2024-04-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0022_environmentalsystem_target_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalsystem',
            old_name='target_level',
            new_name='target_value',
        ),
    ]
