# Generated by Django 4.2.10 on 2024-04-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0023_rename_target_level_environmentalsystem_target_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture_threshold_low', models.FloatField(default=1)),
                ('soil_moisture_threshold_high', models.FloatField(default=100)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_threshold', to='smart_greenhouse_app.sensorunit')),
            ],
        ),
    ]
