# Generated by Django 4.2.10 on 2024-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0025_environmentalsystem_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsystem',
            name='cool_down',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='environmentalsystem',
            name='last_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
