# Generated by Django 4.2.10 on 2024-04-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0026_environmentalsystem_cool_down_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalSystem',
        ),
    ]
