# Generated by Django 4.2.10 on 2024-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0027_delete_externalsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorunit',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
