# Generated by Django 4.2.10 on 2024-12-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0028_sensorunit_additional_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorunit',
            name='additional_data',
        ),
    ]
