# Generated by Django 4.2.10 on 2024-12-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0029_remove_sensorunit_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorunit',
            name='sensor_type',
            field=models.CharField(blank=True, help_text='Dynamic sensor type based on data keys.', max_length=255),
        ),
        migrations.CreateModel(
            name='SensorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Data key (e.g., temperature, humidity).', max_length=50)),
                ('threshold_low', models.FloatField(default=0.0, help_text='Lower threshold.')),
                ('threshold_high', models.FloatField(default=100.0, help_text='Upper threshold.')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='smart_greenhouse_app.sensorunit')),
            ],
            options={
                'unique_together': {('sensor', 'key')},
            },
        ),
    ]
