# Generated by Django 4.2.10 on 2025-01-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0030_alter_sensorunit_sensor_type_sensorthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsystem',
            name='identifier',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
