# Generated by Django 4.2.10 on 2025-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0031_environmentalsystem_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsystem',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
