# Generated by Django 4.2.10 on 2025-01-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0032_environmentalsystem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalsystem',
            name='unique_identifier',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorunit',
            name='unique_identifier',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
