# Generated by Django 4.2.10 on 2025-01-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0034_windowcontrolsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalsystem',
            name='env_type',
            field=models.CharField(choices=[('Cooling', 'Cooling'), ('Heating', 'Heating'), ('Sprinkler', 'Sprinkler'), ('Window', 'Window')], default='Cooling', max_length=10),
        ),
    ]
