# Generated by Django 4.2.10 on 2025-02-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0035_alter_environmentalsystem_env_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilmoisturethreshold',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='HumidityThreshold',
        ),
        migrations.DeleteModel(
            name='SoilMoistureThreshold',
        ),
        migrations.DeleteModel(
            name='TemperatureThreshold',
        ),
    ]
