# Generated by Django 4.2.10 on 2025-04-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0036_remove_soilmoisturethreshold_sensor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalsystem',
            name='cool_down',
        ),
    ]
