# Generated by Django 4.2.10 on 2025-04-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_greenhouse_app', '0037_remove_environmentalsystem_cool_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsystem',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('waiting', 'Waiting'), ('unreachable', 'Unreachable')], default='idle', max_length=20),
        ),
    ]
